source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

inhibit_all_warnings!         #禁止所有警告

target 'HGUIKit_Example' do
  pod 'HGUIKit', :path => '../'
  pod 'YYKit'
  pod 'YTKNetwork'
  pod 'MJExtension'
end

#消除第三方库最低版本的警告，对第三方库进行了判断若DEPLOYMENT_TARGET<10.0就会切换成10.0
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            end
        end
    end
end
